# Generated by Django 6.0 on 2025-12-27 16:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='أدخل رقم جوال/هاتف بصيغة صحيحة (8 إلى 15 رقمًا) ويمكن أن يبدأ بـ +.', regex='^\\+?\\d{8,15}$')])),
                ('is_marketing_opt_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف عميل',
                'verbose_name_plural': 'ملفات العملاء',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('shipping', 'شحن'), ('billing', 'فواتير')], default='shipping', max_length=20)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='أدخل رقم جوال/هاتف بصيغة صحيحة (8 إلى 15 رقمًا) ويمكن أن يبدأ بـ +.', regex='^\\+?\\d{8,15}$')])),
                ('country', models.CharField(default='Saudi Arabia', max_length=80)),
                ('city', models.CharField(default='Riyadh', max_length=80)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('street', models.CharField(max_length=200)),
                ('building_no', models.CharField(blank=True, max_length=30)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'عنوان',
                'verbose_name_plural': 'العناوين',
                'indexes': [models.Index(fields=['user', 'type'], name='accounts_ad_user_id_680b07_idx'), models.Index(fields=['user', 'is_default'], name='accounts_ad_user_id_c8244c_idx')],
            },
        ),
    ]
