# Generated by Django 6.0 on 2025-12-28 16:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='building_no',
            field=models.CharField(blank=True, max_length=30, verbose_name='رقم المبنى'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='الرياض', max_length=80, verbose_name='المدينة'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='المملكة العربية السعودية', max_length=80, verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=120, verbose_name='الحي'),
        ),
        migrations.AlterField(
            model_name='address',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, help_text='تحديد هذا العنوان كعنوان افتراضي', verbose_name='العنوان الافتراضي'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='أدخل رقم جوال أو هاتف بصيغة صحيحة (من 8 إلى 15 رقمًا)، ويمكن أن يبدأ بعلامة +.', regex='^\\+?\\d{8,15}$')], verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='الرمز البريدي'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=200, verbose_name='الشارع'),
        ),
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('shipping', 'عنوان شحن'), ('billing', 'عنوان فواتير')], default='shipping', max_length=20, verbose_name='نوع العنوان'),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='is_marketing_opt_in',
            field=models.BooleanField(default=False, help_text='هل وافق العميل على استقبال العروض والرسائل التسويقية؟', verbose_name='موافق على الرسائل التسويقية'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='أدخل رقم جوال أو هاتف بصيغة صحيحة (من 8 إلى 15 رقمًا)، ويمكن أن يبدأ بعلامة +.', regex='^\\+?\\d{8,15}$')], verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
