# Generated by Django 6.0 on 2025-12-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_public_id',
            field=models.CharField(blank=True, help_text='مثال: products/laptops/macbook_01', max_length=255, verbose_name='معرّف الصورة (Cloudinary)'),
        ),
    ]
