# Generated by Django 6.0 on 2025-12-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_productimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/', verbose_name='الصورة (رفع محلي)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_public_id',
            field=models.CharField(blank=True, help_text='مثال: products/2025/12/abc123', max_length=255, verbose_name='Cloudinary Public ID'),
        ),
    ]
